export interface Product {
  id: string;
  name: string;
  description: string;
  fullDescription: string;
  status: string;
  image: string;
  category: string;
  features: string[];
  applications: string[];
  slug: string;
  packSizes?: string[];
  finish?: string;
  howToApply?: { step: string; title: string; desc: string }[];
  technicalSpecs?: {
    coverage?: string;
    dryingTime?: string;
    finish?: string;
    application?: string;
  };
}

export const products: Product[] = [
  { id: "01", name: "Axis Weather Coat", description: "Precision-engineered protective coating for extreme environmental conditions.", fullDescription: "Axis Weather Coat is a premium protective coating engineered to withstand extreme weather conditions, UV radiation, and chemical exposure.", status: "Active", image: "/AxisWeatherC.png", category: "Protective Coatings", features: ["UV Resistant", "Chemical Resistant", "Weather Proof", "Long-lasting Durability"], applications: ["Industrial Equipment", "Marine Vessels", "Outdoor Structures", "Pipeline Protection"], slug: "axis-weather-coat" },
  { id: "02", name: "Ara Weather Coat", description: "Advanced reactive armor system designed for durability and performance.", fullDescription: "Ara Weather Coat features advanced reactive technology that adapts to environmental conditions, providing superior protection against corrosion and wear.", status: "Active", image: "/AraWeather.png", category: "Protective Coatings", features: ["Self-healing Properties", "Anti-corrosion", "Temperature Resistant", "Flexible Application"], applications: ["Automotive", "Aerospace", "Heavy Machinery", "Infrastructure"], slug: "ara-weather-coat" },
  { id: "03", name: "Tough Tex", description: "Industrial-grade textile technology for maximum resilience and flexibility.", fullDescription: "Tough Tex is an industrial-grade textile coating that combines maximum resilience with flexibility, perfect for high-wear applications.", status: "Active", image: "/Tough_Tex.png", category: "Industrial Textiles", features: ["Tear Resistant", "Waterproof", "Breathable", "High Tensile Strength"], applications: ["Protective Gear", "Industrial Covers", "Tarpaulins", "Tents"], slug: "tough-tex" },
  { id: "04", name: "CRUX SUPRA Fine Finish Wall Putty", description: "Premium fine finish wall putty for smooth, flawless surfaces.", fullDescription: "CRUX SUPRA Fine Finish Wall Putty provides an ultra-smooth base for premium paints, ensuring perfect wall finishing with superior adhesion.", status: "Active", image: "/CRUX_SUPRA_Fine_Finish_Wall_Putty.png", category: "Wall Finishes", features: ["Smooth Finish", "Excellent Adhesion", "Crack Resistant", "Easy Application"], applications: ["Interior Walls", "Exterior Walls", "Commercial Spaces", "Residential Projects"], slug: "crux-supra-fine-finish" },
  { id: "05", name: "CRUX Coarse Finish Wall Putty", description: "Rugged wall putty for textured finishes and surface leveling.", fullDescription: "CRUX Coarse Finish Wall Putty is designed for surface leveling and creating textured finishes on both interior and exterior walls.", status: "Active", image: "/CRUX_Coarse_Finish_Wall_Putty.png", category: "Wall Finishes", features: ["Excellent Coverage", "Surface Leveling", "Textured Finish", "Durable"], applications: ["Exterior Walls", "Textured Finishes", "Repair Work", "Surface Preparation"], slug: "crux-coarse-finish" },
  { id: "06", name: "Buildwell Ready-Mix Plaster", description: "Pre-mixed plaster solution for efficient construction.", fullDescription: "Buildwell Ready-Mix Plaster is a factory-mixed plaster that ensures consistent quality and reduces on-site labor requirements.", status: "Active", image: "/Buildwell_Reay-Mix_Plaster.png", category: "Construction Materials", features: ["Consistent Quality", "Time Saving", "Reduced Waste", "Superior Bonding"], applications: ["Interior Walls", "Exterior Walls", "Ceilings", "Renovation Projects"], slug: "buildwell-ready-mix-plaster" },
  { id: "07", name: "Glossmate Enamel Paint", description: "High-gloss enamel paint for brilliant, long-lasting finish.", fullDescription: "Glossmate Enamel Paint delivers a brilliant, high-gloss finish that resists yellowing and maintains its shine for years.", status: "Active", image: "/Glossmate_Enamel_Paint.png", category: "Decorative Paints", features: ["High Gloss Finish", "Scratch Resistant", "Easy Cleaning", "Weather Resistant"], applications: ["Metal Surfaces", "Wood Work", "Furniture", "Doors & Windows"], slug: "glossmate-enamel" },
  { id: "08", name: "Uniprime Ext", description: "Premium exterior primer for superior paint adhesion.", fullDescription: "Uniprime Ext is a high-performance exterior primer that ensures superior paint adhesion and protects against weathering.", status: "Active", image: "/Uniprime_Ext.png", category: "Primers", features: ["Superior Adhesion", "Alkali Resistant", "Weather Protection", "Seals Surfaces"], applications: ["Exterior Walls", "Concrete Surfaces", "Plastered Walls", "Masonry"], slug: "uniprime-ext" },
  { id: "09", name: "Uniprime", description: "Versatile primer for interior and exterior applications.", fullDescription: "Uniprime is a versatile all-purpose primer that prepares surfaces for optimal paint adhesion and uniform finish.", status: "Active", image: "/Uniprime.png", category: "Primers", features: ["All-purpose", "Quick Drying", "Excellent Adhesion", "Seals Porous Surfaces"], applications: ["Interior Walls", "Exterior Walls", "Wood", "Metal"], slug: "uniprime" },
  { id: "10", name: "Jet Emulsion", description: "Smooth emulsion paint for elegant interior finishes.", fullDescription: "Jet Emulsion provides a smooth, elegant finish for interior walls with excellent washability and color retention.", status: "Active", image: "/JetEmu.png", category: "Emulsion Paints", features: ["Smooth Finish", "Washable", "Color Retention", "Low VOC"], applications: ["Living Rooms", "Bedrooms", "Offices", "Hotels"], slug: "jet-emulsion" },
  { id: "11", name: "Metalock Yellow Pro", description: "Professional grade yellow metal coating for industrial use.", fullDescription: "Metalock Yellow Pro is a professional-grade coating specifically formulated for metal surfaces requiring high visibility and protection.", status: "Active", image: "/Metalock_Yellow_Pro.png", category: "Industrial Coatings", features: ["High Visibility", "Corrosion Resistant", "UV Stable", "Industrial Grade"], applications: ["Safety Equipment", "Industrial Machinery", "Markings", "Heavy Equipment"], slug: "metalock-yellow-pro" },
  { id: "12", name: "Metalock Yellow", description: "Standard yellow metal coating for general applications.", fullDescription: "Metalock Yellow provides reliable protection and high-visibility finish for general metal coating applications.", status: "Active", image: "/Metalock_Yellow.png", category: "Industrial Coatings", features: ["Durable Finish", "Good Coverage", "Weather Resistant", "Easy Application"], applications: ["Metal Structures", "Pipes", "Equipment", "General Metal Work"], slug: "metalock-yellow" },
  { id: "13", name: "Metalock Red Pro", description: "Premium red industrial coating for heavy-duty applications.", fullDescription: "Metalock Red Pro delivers superior protection and high-visibility red finish for heavy-duty industrial applications.", status: "Active", image: "/Metalock_Red_Pro.png", category: "Industrial Coatings", features: ["Heavy-duty Protection", "Chemical Resistant", "High Visibility", "Long-lasting"], applications: ["Fire Safety Equipment", "Heavy Machinery", "Industrial Piping", "Warning Markings"], slug: "metalock-red-pro" },
  { id: "14", name: "Metalock Red", description: "Standard red metal coating for general industrial use.", fullDescription: "Metalock Red offers reliable protection and standard red finish for general industrial metal coating requirements.", status: "Active", image: "/Metalock_Red.png", category: "Industrial Coatings", features: ["Good Adhesion", "Weather Resistant", "Economical", "Easy to Apply"], applications: ["General Metal Surfaces", "Maintenance Work", "Repairs", "Touch-ups"], slug: "metalock-red" },
  { id: "15", name: "Oil Paint Premium", description: "Premium oil-based paint for superior finish and durability.", fullDescription: "Oil Paint Premium delivers a superior, durable finish with excellent flow and leveling properties for professional results.", status: "Active", image: "/Oil_Paint_premium.png", category: "Oil Paints", features: ["Superior Flow", "Excellent Durability", "High Gloss Option", "Smooth Finish"], applications: ["Fine Woodwork", "Furniture", "Decorative Surfaces", "Artistic Projects"], slug: "oil-paint-premium" },
  { id: "16", name: "Eco Acrylic Distemper", description: "Eco-friendly acrylic distemper for interior walls.", fullDescription: "Eco Acrylic Distemper is an environmentally friendly, water-based distemper perfect for interior walls with excellent coverage.", status: "Active", image: "/Eco_Acrylic_Distemper.png", category: "Distempers", features: ["Eco-friendly", "Water-based", "Excellent Coverage", "Breathable Finish"], applications: ["Interior Walls", "Ceilings", "Low-traffic Areas", "Residential Spaces"], slug: "eco-acrylic-distemper" },
  { id: "17", name: "Decorx Acrylic Distemper", description: "Decorative acrylic distemper for enhanced interior aesthetics.", fullDescription: "Decorx Acrylic Distemper combines decorative appeal with durable protection for enhanced interior wall aesthetics.", status: "Active", image: "/Decorx_Acrylic_Distemper.png", category: "Distempers", features: ["Decorative Finish", "Durable", "Easy Application", "Good Coverage"], applications: ["Interior Decoration", "Feature Walls", "Commercial Spaces", "Hospitality"], slug: "decorx-acrylic-distemper" },
  { id: "18", name: "Aquaris Supra", description: "Premium waterproofing solution for superior protection.", fullDescription: "Aquaris Supra provides premium waterproofing protection for roofs, terraces, and other exposed surfaces.", status: "Active", image: "/Aquaris_Supra.png", category: "Waterproofing", features: ["Superior Waterproofing", "Elastic Properties", "UV Resistant", "Long-lasting"], applications: ["Roofs", "Terraces", "Balconies", "Water Tanks"], slug: "aquaris-supra" },
  { id: "19", name: "Aquaproof", description: "Reliable waterproofing compound for construction.", fullDescription: "Aquaproof is a reliable waterproofing compound that provides effective protection against water ingress in construction projects.", status: "Active", image: "/Aquaproof.png", category: "Waterproofing", features: ["Effective Protection", "Easy Application", "Cost-effective", "Versatile Use"], applications: ["Basements", "Bathrooms", "Wet Areas", "Foundation Walls"], slug: "aquaproof" },
  { id: "20", name: "Decorprime", description: "High-performance decorative primer for premium finishes.", fullDescription: "Decorprime is a high-performance primer that ensures premium decorative finishes with enhanced durability and adhesion.", status: "Active", image: "/Decoprime.png", category: "Primers", features: ["Premium Finish", "Enhanced Adhesion", "Seals Surfaces", "Quick Drying"], applications: ["Premium Interiors", "Decorative Projects", "High-end Finishes", "Architectural Work"], slug: "decorprime" },
  { id: "21", name: "DuraGuard Exterior", description: "Heavy-duty exterior paint for maximum protection.", fullDescription: "DuraGuard Exterior provides maximum protection against harsh weather conditions with exceptional durability and color retention.", status: "Active", image: "/DuraGuard_Exterior.png", category: "Exterior Paints", features: ["Maximum Protection", "Weather Resistant", "Color Retention", "Anti-fungal"], applications: ["Exterior Walls", "Facades", "Boundary Walls", "Commercial Buildings"], slug: "duraguard-exterior" },
  { id: "22", name: "DuraGuard Interior", description: "Durable interior paint for high-traffic areas.", fullDescription: "DuraGuard Interior offers exceptional durability for high-traffic interior areas while maintaining an elegant finish.", status: "Active", image: "/DuraGuard_Interior.png", category: "Interior Paints", features: ["Scrub Resistant", "Stain Resistant", "Easy Cleaning", "Durable Finish"], applications: ["Hallways", "Corridors", "Kitchens", "High-traffic Areas"], slug: "duraguard-interior" },
  { id: "23", name: "Eva Emulsion", description: "Smooth emulsion with excellent coverage properties.", fullDescription: "Eva Emulsion delivers smooth, even coverage with excellent hiding power and an elegant matte finish.", status: "Active", image: "/Eva_Emulsion.png", category: "Emulsion Paints", features: ["Excellent Coverage", "Smooth Finish", "Matte Appearance", "Good Hiding Power"], applications: ["Interior Walls", "Ceilings", "Bedrooms", "Living Areas"], slug: "eva-emulsion" },
  { id: "24", name: "Zodiac Emulsion", description: "Premium emulsion for luxurious interior finishes.", fullDescription: "Zodiac Emulsion provides a luxurious, premium finish for discerning interior design projects requiring exceptional quality.", status: "Active", image: "/Zodiac_Emulsion.png", category: "Emulsion Paints", features: ["Luxurious Finish", "Premium Quality", "Excellent Durability", "Rich Colors"], applications: ["Luxury Homes", "Premium Offices", "Hotels", "Showrooms"], slug: "zodiac-emulsion" },
];

